### PR TITLE
update supported_platforms.md with references to el9

### PR DESCRIPTION
**Pull request by mwestphall**

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
This LGTM! Where'd you get the minor version for the EL9 build platform?

**Comment by mwestphall** [comment]
> This LGTM! Where'd you get the minor version for the EL9 build platform?

https://access.redhat.com/articles/3078 . Based on this it looks like the documentation will become outdated mid-November of this year

**Comment by brianhlin** [comment]
CI failures unrelated, merging

**Comment by brianhlin** [comment]
Ah yes that's the latest minor release available but that does assume that we're appropriately building on the latest :). @matyasselmeci?

**Comment by matyasselmeci** [comment]
```
% koji list-external-repos | grep r9-BaseOS
dist-r9-BaseOS            https://mirrors.rit.edu/rocky/9/BaseOS/$arch/os/
```
we are in fact always building on the latest. (el7 and el8 are similar)

**Pull request merged**
