### PR TITLE
Document minimum OSPool AP HTCSS version policy (SOFTWARE-5776)

### PR DESCRIPTION
**Pull request by brianhlin**
Let's hold off on merging this until we get the go-ahead. I'd also like the HTCSS release highlights page to emphasize the security releases in some way for bullet 3.

### CODE REVIEW

**Comment by brianhlin** [comment]
@timtheisen will be adding a link to the manual for a table with the supported release lifecycle. We can update the link in the first bullet to point there but I think it'd be ideal to place the same table in https://htcondor.org/htcondor/release-plan/

**Comment by brianhlin** [comment]
@timtheisen @CannonLock one thing to note is that this doc indicates that the 10.0 series is supported https://htcondor.readthedocs.io/en/latest/version-history/introduction-version-history.html#support-life-cycle until August 2024 but you cannot find the 10.0 release highlights here https://htcondor.org/htcondor/release-highlights/

**Comment by timtheisen** [comment]
If you expand the LTS release highlights, the version 10.0 highlights are there. The button is at the bottom of the box.

**Comment by brianhlin** [comment]
@timtheisen I think it'd be worth separating out 10.0 from the 23.0 announcements especially since the 10.0 series is in security only support mode.

**Comment by brianhlin** [comment]
@timtheisen I'd like to be able to point admins of 10.0 HTCondor installations to a page where they can figure out the latest release of 10.0 at a glance. I don't think that it's intuitive that 23.0 and 10.0 are lumped together and they need to click and potentially scroll through 12 or so releases before they find the latest 10.0 release.

**Comment by brianhlin** [comment]
Got the verbal thumbs up from @bbockelm . Merging

**Pull request merged**
