### PR TITLE
Fix GHA deprecation warnings (Software-5354)

### PR DESCRIPTION
**Pull request by jtakaki-matc**
Fix set-output GHA deprecation warning in validate-mkdocks.yml

### CODE REVIEW

**Review by brianhlin — APPROVED** [review]
LGTM! FWIW, a single commit for all of these changes would have been fine by me, e.g. "Fix GHA deprecation warnings (SOFTWARE-5354)"

**Comment by brianhlin** [comment]
Ah nevermind, there's a failure that you need to address https://github.com/osg-htc/docs/actions/runs/5327090927/jobs/9653201586?pr=108#step:6:5. I think your other PRs are also affected. I'll leave this as an exercise to the reader 😈

**Comment by jtakaki-matc** [comment]
@brianhlin Fixed error. I will learn how to spell!

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
